jobs: {{cookiecutter.cores}}
verbose: {{cookiecutter.verbose}}
use-singularity: {{cookiecutter.use_singularity}}
use-envmodules: {{cookiecutter.use_envmodules}}
singularity-args: '\-e'
local-cores: {{cookiecutter.cores}}
singularity-prefix: {{cookiecutter.singularity_prefix}}
notebook-listen: '$(hostname -f):8888'
rerun-incomplete: True
keep-going: True
show-failed-logs: True
resources: {{cookiecutter.resources}}
